### ISSUE TITLE
Can't run on an M1. Upgrade iconv dependency.

### ISSUE THREAD

**Issue by scottsykora** [justinklemm/i18n-strings-files#16]
I'm trying to run on an M1 Mac and it seems like the dependency 'iconv' doesn't work. It needs to be updated to 3.0.1. Would it be possible to upgrade the dependency to that version of iconv? Does that break anything?

**Comment by justinklemm** [comment]
Hi Scott, can you submit a PR with the dep update and see if the tests pass?

**Comment by justinklemm** [comment]
Hi there, v2.0.0 has been released which updates iconv to 3.0.1
