### ISSUE TITLE
How to deal with UTF16 encoded Japanese characters in Node

### ISSUE THREAD

**Issue by jonathanpeterwu** [justinklemm/i18n-strings-files#7]
I've been having trouble utilizing a file upload of a Japanese iOS strings file. Did you run into any encoding issues with Japanese Characters

**Comment by justinklemm** [comment]
@jonathanpeterwu I'm not aware of any issues with Japanese characters. Can you give some more details on the issue you're seeing? Snippet of file contents and Node version would also be helpful.

**Comment by jonathanpeterwu** [comment]
@justinklemm. I think we figured out the issue.

Our server was buffering in a UTF-16LE file but displaying it as UTF-8, hence creating jarbled code. We've gone ahead and used formidable to detect decode and reencode the buffer into UTF-8 for proper parsing. thanks!

**Comment by justinklemm** [comment]
@jonathanpeterwu Glad to hear it! I'm going to close this issue. Feel free to re-open if you run into more problems.
